version: "3.7"

services:
  home_page:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home_page/src:ro
    environment:
      - REACT_APP_NAME=myNameSLIME
      - REACT_APP_NOT_SECRET_CODE=re-run
    env_file:
      - ./.env
